### ISSUE TITLE
Sheep

### ISSUE THREAD

**Issue by heaucques** [SheepTester/happynumbers#1]
🐑

**Comment by SheepTester** [comment]
Hi!
:+1: 
:100: 
:football: 
:hamburger: 
:shipit: 
:package:

**Comment by heaucques** [comment]
Hello!
👍 
💯 
🔢 
🐑 
🍧

**Comment by SheepTester** [comment]
:cherries: :tangerine:

# haaaaa

**Comment by heaucques** [comment]
Apple 😄 
🍎 
🍏 
🍎 
🍏

**Comment by SheepTester** [comment]
:toilet: nice profile picture @Vexisle

**Comment by heaucques** [comment]
Yay!
🚽 ?
🚻 ?
🍑 
🍐 
You used your original one

**Comment by SheepTester** [comment]
Check out the [new background](https://sheeptester.github.io/happynumbers/)!

It's based off kahoot.it :stuck_out_tongue_closed_eyes:

**Comment by heaucques** [comment]
Hooray!

**Comment by heaucques** [comment]
I froze the calculator
❓ 
🍭

**Comment by SheepTester** [comment]
@Vexisle I think it's because you entered in a huge number

I'd like to develop an engine to deal with this for the [Eyo Dictionary](https://sheeptester.github.io/eyo-dictionary/) so please make a new issue for the sake of me talking to myself

**Comment by SheepTester** [comment]
ok
